server:
  port: 8081
  servlet:
    context-path: /orderservice

spring:
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.100:8848

feign:
  client:
    config:
      default:
        loggerLevel: FULL